-- Create raw data tables that can be dropped and replaced
-- These tables store the original CSV data

-- 1. Raw voters table - direct import from voter file CSV
-- Schema based on secondvoterfile.csv (August 2024 update)
CREATE TABLE IF NOT EXISTS `proj-roth.voter_data.raw_voters` (
  -- Original voter file columns (80 total)
  id STRING,
  addr_residential_street_name STRING,
  addr_residential_street_number STRING,
  name_first STRING,
  name_middle STRING,
  name_last STRING,
  demo_age INT64,
  demo_race STRING,
  demo_race_confidence STRING,
  demo_gender STRING,
  addr_residential_state STRING,
  addr_residential_city STRING,
  current_voter_registration_intent STRING,
  current_support_score FLOAT64,
  current_tags STRING,
  score_support_generic_dem FLOAT64,
  demo_party STRING,
  registration_status_civitech STRING,
  addr_residential_line1 STRING,
  addr_residential_line2 STRING,
  addr_residential_line3 STRING,
  addr_residential_zip_code STRING,
  county_name STRING,
  email STRING,
  phone_1 STRING,
  phone_2 STRING,
  congressional_name STRING,
  state_house_name STRING,
  state_senate_name STRING,
  precinct_name STRING,
  municipal_name STRING,
  place_name STRING,
  city_council_name STRING,
  voter_type STRING,
  -- Participation columns (all elections 2016-2024)
  -- Note: CSV uses TRUE/FALSE strings, will convert to BOOLEAN on import
  participation_primary_2016 BOOLEAN,
  participation_primary_2017 BOOLEAN,
  participation_primary_2018 BOOLEAN,
  participation_primary_2019 BOOLEAN,
  participation_primary_2020 BOOLEAN,
  participation_primary_2021 BOOLEAN,
  participation_primary_2022 BOOLEAN,
  participation_primary_2023 BOOLEAN,
  participation_primary_2024 BOOLEAN,
  participation_general_2016 BOOLEAN,
  participation_general_2017 BOOLEAN,
  participation_general_2018 BOOLEAN,
  participation_general_2019 BOOLEAN,
  participation_general_2020 BOOLEAN,
  participation_general_2021 BOOLEAN,
  participation_general_2022 BOOLEAN,
  participation_general_2023 BOOLEAN,
  participation_general_2024 BOOLEAN,
  -- Vote columns (primary votes by party)
  vote_primary_dem_2016 BOOLEAN,
  vote_primary_rep_2016 BOOLEAN,
  vote_primary_dem_2017 BOOLEAN,
  vote_primary_rep_2017 BOOLEAN,
  vote_primary_dem_2018 BOOLEAN,
  vote_primary_rep_2018 BOOLEAN,
  vote_primary_dem_2019 BOOLEAN,
  vote_primary_rep_2019 BOOLEAN,
  vote_primary_dem_2020 BOOLEAN,
  vote_primary_rep_2020 BOOLEAN,
  vote_primary_dem_2021 BOOLEAN,
  vote_primary_rep_2021 BOOLEAN,
  vote_primary_dem_2022 BOOLEAN,
  vote_primary_rep_2022 BOOLEAN,
  vote_primary_dem_2023 BOOLEAN,
  vote_primary_rep_2023 BOOLEAN,
  vote_primary_dem_2024 BOOLEAN,
  vote_primary_rep_2024 BOOLEAN,
  -- Other vote columns (may contain vote method like "IN PERSON", "MAIL", etc.)
  vote_other_2016 STRING,
  vote_other_2017 STRING,
  vote_other_2018 STRING,
  vote_other_2019 STRING,
  vote_other_2020 STRING,
  vote_other_2021 STRING,
  vote_other_2022 STRING,
  vote_other_2023 STRING,
  vote_other_2024 STRING,
  notes STRING,
  -- Import metadata
  import_batch_id STRING,
  import_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY county_name, demo_party;

-- 2. Raw donations table - direct import from donations CSV
CREATE TABLE IF NOT EXISTS `proj-roth.voter_data.raw_donations` (
  committee_name STRING,
  full_name STRING,
  first_name STRING,
  middle_name STRING,
  last_name STRING,
  suffix STRING,
  address_1 STRING,
  address_2 STRING,
  city STRING,
  state STRING,
  zip STRING,
  employer STRING,
  occupation STRING,
  contribution_amount NUMERIC,
  election_type STRING,
  election_year INT64,
  -- Import metadata
  import_batch_id STRING,
  import_timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
)
CLUSTER BY state, zip;